PLATFORM_NAME='cursor'
PLATFORM_INPUTS='platforms/cursor/mcp.json.template
platforms/cursor/rules/projectpal.md
platforms/cursor/cursor-mcp/package.json
platforms/cursor/cursor-mcp/bin/projectpal-cursor-mcp'
PLATFORM_OUTPUTS='build/cursor/mcp.json
build/cursor/.cursor/rules/projectpal.md
build/cursor/cursor-mcp/package.json
build/cursor/cursor-mcp/bin/projectpal-cursor-mcp
build/cursor/cursor-mcp/rules/projectpal.md'
